      - name: Commit Results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Tenta baixar as ultimas mudanças para evitar conflito
          git pull --rebase || true
          
          # Força adição de tudo na pasta results
          git add -f results/*
          
          # Debug: Mostra o que vai ser commitado
          echo "Status do Git:"
          git status
          
          # Commita e Pusha
          git commit -m "New Backtest Run $(date +'%Y-%m-%d %H:%M')" || echo "Nada mudou, sem commit."
          git push
          
